baseURL = 'https://owen.cafe/'
languageCode = 'en'
title = 'owen.cafe'
theme = 'owen.cafe'
relativeURLs = true

[menu]
[[menu.main]]
  name = 'Github'
  url = 'https://github.com/414owen/'
  weight = 4

[markup.goldmark.renderer]
unsafe = true
