baseURL = 'https://owen.cafe/'
languageCode = 'en'
title = 'owen.cafe'
theme = 'owen.cafe'

[menu]
[[menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 2

[[menu.main]]
  name = 'Github'
  url = 'https://github.com/414owen/'
  weight = 5

[[menu.main]]
  name = 'CV'
  url = '/cv.pdf'
  weight = 7

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[params]
Description = "Owen's personal website and portfolio"
