baseURL = 'https://owen.cafe/'
languageCode = 'en'
title = 'owen.cafe'
theme = 'owen.cafe'

[menu]
[[menu.main]]
  name = 'Posts'
  pageref = '/posts'
  weight = 2

# [[menu.main]]
#   name = 'RSS'
#   url = '/index.xml'
#   weight = 3

[[menu.main]]
  name = 'Github'
  url = 'https://github.com/414owen/'
  weight = 6

[[menu.main]]
  name = 'CV'
  url = '/cv.pdf'
  weight = 8

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[params]
Description = "Owen's personal website and portfolio"
